version: '3.7'

networks:
  server-network:
    driver: bridge

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./sample-backend
      target: development
    volumes:
      - .:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    ports:
      - '3000:3000'
    networks:
      - server-network
    command: npm run start:dev
    links:
      - communication
      - analytics
    depends_on:
      - communication
      - analytics
  communication:
    container_name: micro_service_comm
    restart: always
    build:
      context: ./sample-communication
      target: development
    volumes:
      - .:/usr/src/app/communication
      - /usr/src/app/communication/node_modules       
    ports:
      - "3010:3010"
    networks:
      - server-network           
    command: npm run start:dev  
  analytics:
    container_name: micro_service_anly
    restart: always
    build:
      context: ./sample-analytics
      target: development
    volumes:
      - .:/usr/src/app/analytics
      - /usr/src/app/analytics/node_modules       
    ports:
      - "3011:3011"
    networks:
      - server-network           
    command: npm run start:dev      